image: docker:latest

stages:
- build
- test
- run

services:
  - docker:dind

build-docker-images:
  stage: build
  script:
  - docker build -t avimehenwal/cherrypy-app:5 .
  - docker build -f Test_Dockerfile -t avimehenwal/test-cherrypy-app:2 .

app-test:
  stage: test
  script:
  - docker run --name testcpy --rm -it avimehenwal/test-cherrypy-app:2

prod-app-run:
  stage: run
  script:
  - docker run -ti --name cpy -d -p 8081:8081 avimehenwal/cherrypy-app:5 app.py
