image: docker:latest

stages:
- build
- test

services:
  - docker:dind

before_script:
  - docker run --rm registry.gitlab.com/avimehenwal/cherrypy-app app.py

app-test:
  stage: test
  image: python3.5
  script:
  - pip install -r test-requirements.txt
  - python test_app.py
