image: docker:latest

stages:
- build
- test

services:
  - docker:dind

build-app:
  stage: build
  script:
  - docker build -f Test_Dockerfile -t avimehenwal/test-cherrypy-app .
  - docker tag avimehenwal/test-cherrypy-app avimehenwal/test-cherrypy-app:latest
  - docker push avimehenwal/test-cherrypy-app

app-test:
  stage: test
  script:
  - docker run avimehenwal/test-cherrypy-app:3
