image: docker:latest

stages:
- test
- build

services:
  - docker:dind

docker_build:
  stage: build
  script:
  - docker images ls -a
  - docker build -t avimehenwal/cherrypy-app:avi .
  - docker images ls -a
