image: docker:latest

stages:
- test

services:
  - docker:dind
  - docker run -d -p 8080:8080 registry.gitlab.com/avimehenwal/cherrypy-app app.py

app-test:
  stage: test
  image: python:3.5
  script:
  - pip install -r test-requirements.txt
  - python test_app.py
