version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: docker build -f Test_Dockerfile -t avimehenwal/test-cherrypy-app .
      - run: docker run avimehenwal/test-cherrypy-app
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKERHUB_ID -p $DOCKERHUB_PASS
      - run: docker build -t $CIRCLE_PROJECT_USERNAME/auto-cherrypy-app:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
      - run: docker push $CIRCLE_PROJECT_USERNAME/auto-cherrypy-app:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
