version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -f Test_Dockerfile -t avimehenwal/test-cherrypy-app .
      - run: docker run avimehenwal/test-cherrypy-app
